name: Publish .NET Library to NuGet.org

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Adjust to your version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build library project
      run: dotnet build ConfigManager/ConfigManager.csproj --configuration Release --no-restore

    - name: Pack NuGet package (only library)
      run: dotnet pack ConfigManager/ConfigManager.csproj --configuration Release --no-build -o ./artifacts

    - name: Push to NuGet.org
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
